include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    - avoid_print
    - avoid_empty_else
    - avoid_shadowing_type_parameters
    - avoid_as
    - camel_case_types
    - constant_identifier_names
    - annotate_overrides
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - always_require_non_null_named_parameters
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_specify_types
    - avoid_function_literals_in_foreach_calls
    - avoid_returning_null
    - prefer_typing_uninitialized_variables
    - unnecessary_this
    - unnecessary_new
    - unnecessary_const
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_generic_function_type_aliases
    - prefer_is_not_empty
    - prefer_collection_literals
    - prefer_single_quotes
    - slash_for_doc_comments
    - unnecessary_brace_in_string_interps
    - unnecessary_lambdas
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_implementing_value_types
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_catches
    - empty_statements
    - exhaustive_cases
    - prefer_null_aware_operators
    - unnecessary_parenthesis
    - use_is_even_rather_than_modulo